INSERT INTO Diagnostico(Diagnosticocol) values('intelectual');
INSERT INTO Diagnostico(Diagnosticocol) values('parálisis de bell');
INSERT INTO Diagnostico(Diagnosticocol) values('física');
INSERT INTO Diagnostico(Diagnosticocol) values('retraso en el desarrollo psicomotriz');
INSERT INTO Diagnostico(Diagnosticocol) values('intelectual leve');
INSERT INTO Diagnostico(Diagnosticocol) values('retraso del lenguaje');
INSERT INTO Diagnostico(Diagnosticocol) values('visual');
INSERT INTO Diagnostico(Diagnosticocol) values('espectro autista');
INSERT INTO Diagnostico(Diagnosticocol) values('hemiplejia');
INSERT INTO Diagnostico(Diagnosticocol) values('discapacidad visual');
INSERT INTO Diagnostico(Diagnosticocol) values('intelectual moderado');
INSERT INTO Diagnostico(Diagnosticocol) values('autismo');
INSERT INTO Diagnostico(Diagnosticocol) values('pci');
INSERT INTO Diagnostico(Diagnosticocol) values('distrofia muscular');
INSERT INTO Diagnostico(Diagnosticocol) values('auditiva');
INSERT INTO Diagnostico(Diagnosticocol) values('mielomeningocele');
INSERT INTO Diagnostico(Diagnosticocol) values('diplejia espástica');
INSERT INTO Diagnostico(Diagnosticocol) values('lenguaje');
INSERT INTO Diagnostico(Diagnosticocol) values('retraso en el lenguaje');
INSERT INTO Diagnostico(Diagnosticocol) values('psicosocial');
INSERT INTO Diagnostico(Diagnosticocol) values('retraso en el desarrollo');
INSERT INTO Diagnostico(Diagnosticocol) values('trastorno del espectro autista');
INSERT INTO Diagnostico(Diagnosticocol) values('displasia cerebral');
INSERT INTO Diagnostico(Diagnosticocol) values('luxación congénita de las caderas');
INSERT INTO Diagnostico(Diagnosticocol) values('retraso mental moderado');
INSERT INTO Diagnostico(Diagnosticocol) values('craneosinostosis');
INSERT INTO Diagnostico(Diagnosticocol) values('moderado');
INSERT INTO Diagnostico(Diagnosticocol) values('lesión medular');
INSERT INTO Diagnostico(Diagnosticocol) values('deficiencia auditiva');
INSERT INTO Diagnostico(Diagnosticocol) values('microcefalia');
INSERT INTO Diagnostico(Diagnosticocol) values('encefalopatía');
INSERT INTO Diagnostico(Diagnosticocol) values('retraso psicomotor');
INSERT INTO Diagnostico(Diagnosticocol) values('osteogénesis imperfecta');
INSERT INTO Diagnostico(Diagnosticocol) values('discapacidad intelectual');
INSERT INTO Diagnostico(Diagnosticocol) values('síndrome de down');
INSERT INTO Diagnostico(Diagnosticocol) values('retardo mental');
INSERT INTO Diagnostico(Diagnosticocol) values('mielomeningocele + hidrocefalia');
INSERT INTO Diagnostico(Diagnosticocol) values('imc');
INSERT INTO Diagnostico(Diagnosticocol) values('síndrome convulsivo');
INSERT INTO Diagnostico(Diagnosticocol) values('deficiencia en el lenguaje');
INSERT INTO Diagnostico(Diagnosticocol) values('deficiencia de lenguaje');
INSERT INTO Diagnostico(Diagnosticocol) values('tdah');
INSERT INTO Diagnostico(Diagnosticocol) values('hipoacusia');
INSERT INTO Diagnostico(Diagnosticocol) values('retraso en el desarrollo psicomotor');
INSERT INTO Diagnostico(Diagnosticocol) values('epilepsia');
INSERT INTO Diagnostico(Diagnosticocol) values('ataxia cerebral');
